Notes/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.notes.urls')),
]

apps/notes/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from apps.notes.views import *
app_name = 'notes'

urlpatterns = [
	path('sign_up/', register.as_view(), name='sign_up'),
	#
	path('log_in/', log_in, name='log_in'),
	#
	path('log_out/', log_out, name='log_out'),
	#
	path('', views.index, name='index'),
	# ex: /polls/5/
	path('<int:id>/', views.detail, name='detail'),
	#
	path('category/create/',category_create.as_view(), name='category_create'),
	#
	path('category/list/',category_list.as_view(), name='category_list'),
	#
	path('category/update/<int:pk>/',category_update.as_view(), name='category_update'),
	#
	path('category/delete/<int:pk>/',category_delete.as_view(), name='category_delete'),
	#
	path('tag/create/',tag_create, name='tag_create'),
	#
	path('tag/list/',tag_list, name='tag_list'),
	#
	path('tag/update/<int:pk>/',tag_update, name='tag_update'),
	#
	path('tag/delete/<int:pk>/',tag_delete, name='tag_delete'),
	#
	path('note/create/',note_create.as_view(), name='note_create'),
	#
	path('note/list/',note_list.as_view(), name='note_list'),
	#
	path('note/update/<int:pk>/',note_update.as_view(), name='note_update'),
	#
	path('note/delete/<int:pk>/',note_delete.as_view(), name='note_delete'),
	#
	path('note/detail/<int:pk>/',note_detail.as_view(), name='note_detail'),
]

apps/notes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Tag(models.Model):
	tag = models.CharField(max_length=15)
	def __str__(self):
		return '{}'.format(self.tag)


class Category(models.Model):
	category = models.CharField(max_length=10)
	def __str__(self):
		return '{}'.format(self.category)

class Note(models.Model):
	VISIBILITY_TYPE = (
	(0, 'Private'),
	(1, 'Public'),
	)
	title = models.CharField(max_length=50)
	content = models.TextField()
	visibility = models.IntegerField(default=0 , choices=VISIBILITY_TYPE)
	tags =  models.ManyToManyField(Tag, blank=True)
	category = models.ForeignKey(Category, blank=True,
								null=True,on_delete=models.CASCADE)
	user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)

	@property
	def visible_type(self):
		if self.visibility is 0:
			return 'Private'
		else:
			return 'Public'
			
	@property
	def all_tags(self):
		list=[]
		for item in self.tags.all():
			list.append(item.tag)
		return list

apps/notes/forms.py
from django import forms
from apps.notes.models import Note,Tag,Category
from django.contrib.auth.models import User

class TagForm(forms.ModelForm):
	class Meta:
		model = Tag
		fields = [
			'tag',
		]
		labels = {
			'tag': 'Tag',
		}
		widgets = {
			'tag': forms.TextInput(attrs={'class':'form-control'}),
		}

class NoteForm(forms.ModelForm):
	class Meta:
		model = Note
		fields = [
			'title',
			'content',
			'visibility',
			'category',
			'tags',
		]
		labels = {
			'title': 'Title',
			'content': 'Content',
			'visibility': 'Visibility',
			'category': 'Categories',
			'tags': 'Tags',
		}
		widgets = {
			'title': forms.TextInput(attrs={'class':'form-control'}),
			'content': forms.Textarea(attrs={'class':'form-control','rows':'5'}),
			'visibility': forms.Select(attrs={'class':'form-control'}),
			'category': forms.Select(attrs={'class':'form-control'}),
			'tags': forms.CheckboxSelectMultiple(attrs={'class':''}),
		}

class CategoryForm(forms.ModelForm):
	class Meta:
		model = Category
		fields = [
			'category',
		]
		labels = {
			'category': 'Category',
		}
		widgets = {
			'category': forms.TextInput(attrs={'class':'form-control'}),
		}

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = [
				'username',
				'password',
				'email',
			]
		labels = {
				'username': 'Username',
				'password': 'Password',
				'email': 'E-mail',
		}
		widgets = {
			'username': forms.TextInput(attrs={'class':'form-control'}),
			'password': forms.PasswordInput(attrs={'class':'form-control'}),
			'email': forms.EmailInput(attrs={'class':'form-control'}),
		}

apps/notes/views.py
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView,ListView,UpdateView, DeleteView
from django.views.generic import TemplateView,View,DetailView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from apps.notes.forms import *
from .models import *
# Create your views here.

def index(request):
		try:
			public_notes = Note.objects.filter(visibility=1).order_by('-id')
		except Note.DoesNotExist:
			raise Http404("Note does not exist")
		return render(request, 'index.html', {'list_notes': public_notes})

class category_create(LoginRequiredMixin,CreateView):
	login_url = '/log_in/'
	model = Category
	form_class = CategoryForm
	template_name = 'notes/category_create.html'
	success_url = reverse_lazy('notes:category_list')
	'''
	# ,UserPassesTestMixin
	# determines if the user is part of the staff
	def test_func(self):
		if self.request.user.is_staff:
			return True
	'''


class category_list(LoginRequiredMixin,ListView):
	login_url = '/log_in/'
	model = Category

	def get_queryset(self):
		return Category.objects.order_by('id')

class category_update(LoginRequiredMixin,UpdateView):
	login_url = '/log_in/'
	model = Category
	fields = ['category']
	template_name_suffix = '_update'
	success_url = reverse_lazy('notes:category_list')

class category_delete(LoginRequiredMixin,DeleteView):
	login_url = '/log_in/'
	model = Category
	template_name_suffix = '_delete'
	success_url = reverse_lazy('notes:category_list')

@login_required(login_url='/log_in/')
def tag_create(request):
	if request.method == 'POST':
		form = TagForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('notes:tag_list')
	else:
		form = TagForm()
	return render(request, 'notes/tag_create.html', {'form':form})

@login_required(login_url='/log_in/')
def tag_list(request):
	tag = Tag.objects.all().order_by('id')
	tags = {'tags':tag}
	return render(request, 'notes/tag_list.html', tags)

@login_required(login_url='/log_in/')
def tag_update(request, pk):
	tag = Tag.objects.get(id=pk)
	if request.method == 'GET':
		form = TagForm(instance=tag)
	else:
		form = TagForm(request.POST, instance=tag)
		if form.is_valid():
			form.save()
		return redirect('notes:tag_list')
	return render(request, 'notes/tag_update.html', {'form':form})

@login_required(login_url='/log_in/')
def tag_delete(request, pk):
	tag = Tag.objects.get(id=pk)
	if request.method == 'POST':
		tag.delete()
		return redirect('notes:tag_list')
	return render(request, 'notes/tag_delete.html', {'tag':tag})

class note_create(LoginRequiredMixin,CreateView):
	login_url = '/log_in/'
	model = Note
	form_class = NoteForm
	template_name = 'notes/note_create.html'
	success_url = reverse_lazy('notes:note_list')

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		if form.is_valid():
			note = form.save()
			note.user = self.request.user
			note.save()
			return HttpResponseRedirect(self.get_success_url())
		#return render(request, 'notes/note_create.html', {'error':'Invalid data in form'})
		return self.render_to_response(self.get_context_data(form=form))

class note_list(LoginRequiredMixin,ListView):
	#redirect_field_name = 'redirect_to'
	login_url = '/log_in/'
	model = Note

	def get_queryset(self):
		return Note.objects.filter(user=self.request.user).order_by('-id')
	'''
	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(note_list, self).get_context_data(**kwargs)
		for note in context['note_list']:
			#note_tags is created in the object to place all related tags
			note.note_tags = note.tags.all()
		return context
	'''

class note_detail(LoginRequiredMixin,DetailView):
	login_url = '/log_in/'
	model = Note
	template_name = 'notes/note_detail.html'
	context_object_name = 'note'
	#queryset = Note.objects.all()

class note_update(LoginRequiredMixin,UserPassesTestMixin,UpdateView):
	login_url = '/log_in/'
	model = Note
	form_class = NoteForm
	template_name_suffix = '_update'
	success_url = reverse_lazy('notes:note_list')

	def test_func(self):
		note=Note.objects.get(id=self.get_object().pk)
		if note.user == self.request.user:
			return True
		else:
			return False

class note_delete(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
	login_url = '/log_in/'
	model = Note
	template_name_suffix = '_delete'
	success_url = reverse_lazy('notes:note_list')

	def test_func(self):
		note=Note.objects.get(id=self.get_object().pk)
		if note.user == self.request.user:
			return True
		else:
			return False

class register(CreateView):
	model = User
	template_name = 'register/sign_up.html'
	form_class = UserForm
	success_url = reverse_lazy('notes:note_list')

	def get_context_data(self, **kwargs):
		context = super(register, self).get_context_data(**kwargs)
		if 'form' not in context:
			context['form'] = self.form_class(self.request.GET)
		return context

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		if form.is_valid():
			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_active:
					login(request, user)
					return HttpResponseRedirect(self.get_success_url())

		return self.render_to_response(self.get_context_data(form=form))

def log_in(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('notes:note_list') #render(request, 'notes/note_list.html')
			else:
				return render(request, 'register/log_in.html',
								{'error_message': 'Your account has been disabled'})
		else:
			return render(request, 'register/log_in.html',
								{'error_message': 'Invalid login'})
	return render(request, 'register/log_in.html')

@login_required(login_url='/log_in/')
def log_out(request):
	logout(request)
	return redirect('notes:index')


def detail(request, id):
	return HttpResponse("Parametro recibido:  %s." % id)

apps/notes/templates/notes/category_create.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">

						<form method="post">
							{% csrf_token %}
							<div class="form-group">
								{{ form }}
							</div>
							<button type="submit">Add</button>
						</form>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/category_delete.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">
						<form method="post">
							{% csrf_token %}
							<p>Are you sure you want to delete "{{ object }}"?</p>
							<input type="submit" value="Confirm">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/category_list.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-6">
					<div class="block">
						<a href="{% url 'notes:category_create' %}" class="badge badge-light mb-2">
							<h3>Add Category</h3>
						</a>
						<table class="table table-striped">
							<thead class="thead-dark">
								<tr>
									<th scope="col">#</th>
									<th scope="col"></th>
									<th scope="col">Category</th>
								</tr>
							</thead>
							<tbody>
								{% for item in object_list %}
									<tr>
										<th scope="row">
											<a class="badge badge-danger" href="{% url 'notes:category_delete' item.id %}">
													X
											</a>
										</th>
										<td>
											<h4>
												<a class="badge badge-primary" href="{% url 'notes:category_update' item.id %}">
														Edit
												</a>
											</h4>
										</td>
										<td><h4>{{item.category}}</h4></td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/category_update.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">
						<form method="post">
							{% csrf_token %}
							{{ form.as_p }}
							<input type="submit" value="Update">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/note_create.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-6">
					<div class="block">

						<form method="post">
							{% csrf_token %}

							<div class="form-group">
									{{ form.title.errors }}
									<label for="{{ form.title.id_for_label }}">Your title:</label>
									{{ form.title }}
							</div>
							<div class="form-group">
									{{ form.content.errors }}
									<label for="{{ form.content.id_for_label }}">Your content:</label>
									{{ form.content }}
							</div>
							<div class="form-group">
									{{ form.visibility.errors }}
									<label for="{{ form.visibility.id_for_label }}">Your visibility:</label>
									{{ form.visibility }}
							</div>
							<div class="form-group">
									{{ form.category.errors }}
									<label for="{{ form.category.id_for_label }}">Your category:</label>
									{{ form.category }}
							</div>
							<div class="custom-control custom-checkbox">
									{{ form.tags.errors }}
									<label for="{{ form.tags.id_for_label }}">Your tags:</label>
									{{ form.tags }}
							</div>
							<button type="submit">Add</button>
						</form>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/note_delete.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-6">
					<div class="block">
						<form method="post">
							{% csrf_token %}
							<p>Are you sure you want to delete "{{ object.title }}"?</p>
							<input type="submit" value="Confirm">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/note_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
	<div class="col-sm">
		<div class="container-fluid">
			<div class="row">
				<div class="col-sm-12">
					<div class="block">
						<a href="{% url 'notes:note_create' %}" class="badge badge-light mb-2">
							<h3>Add Note</h3>
						</a>
						<form>
							<div class="form-group">
								<input type="text" disabled class="form-control" value="{{ note.title }}">
							</div>
							<div class="form-group">
								<blockquote class="blockquote text-center">
								  <p class="mb-0">
											{{ note.content }}
									</p>
								</blockquote>
							</div>
							<div class="form-group">
								<input type="text" disabled class="form-control" value="{{ note.visible_type }}">
							</div>
							<div class="form-group">
								<input type="text" disabled class="form-control" value="{{ note.category }}">
							</div>
							<div class="form-group">
								<ul class="list-group">
									{% for tag in note.all_tags %}
										<li class="list-group-item list-group-item-dark">{{tag}}</li>
									{% endfor %}
								</ul>
							</div>
						</form>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/note_list.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm-12">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-12">
					<div class="block">
						<a href="{% url 'notes:note_create' %}" class="badge badge-light mb-2">
							<h3>Add Note</h3>
						</a>
						<table class="table table-striped">
							<thead class="thead-dark">
								<tr>
									<th scope="col">#</th>
									<th scope="col"></th>
									<th scope="col">Title</th>
									<th scope="col">Visibility</th>
									<!-- <th scope="col">Content</th> -->
									<th scope="col">Category</th>
									<th scope="col">Tags</th>
								</tr>
							</thead>
							<tbody>
								{% for item in object_list %}
									<tr>
										<th scope="row">
											<a class="badge badge-danger" href="{% url 'notes:note_delete' item.id %}">
													X
											</a>
										</th>
										<td>
											<h4>
												<a class="badge badge-primary" href="{% url 'notes:note_update' item.id %}">
														Edit
												</a>
											</h4>
										</td>
										<td>
											<h4>
												<a class="nav-link" href="{% url 'notes:note_detail' item.id %}">
														{{item.title}}
												</a>
											</h4>
										</td>
										<!--<td><h4>{{item.content}}</h4></td> -->
										<td><h4>{{item.visible_type}}</h4></td>
										<td><h4>{{item.category}}</h4></td>
										<td>
											{% for tag in item.all_tags %}
												<h5>{{tag}}</h5>
											{% endfor %}
										</td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/note_update.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-6">
					<div class="block">

						<form method="post">
							{% csrf_token %}

							<div class="form-group">
									{{ form.title.errors }}
									<label for="{{ form.title.id_for_label }}">Your title:</label>
									{{ form.title }}
							</div>
							<div class="form-group">
									{{ form.content.errors }}
									<label for="{{ form.content.id_for_label }}">Your content:</label>
									{{ form.content }}
							</div>
							<div class="form-group">
									{{ form.visibility.errors }}
									<label for="{{ form.visibility.id_for_label }}">Your visibility:</label>
									{{ form.visibility }}
							</div>
							<div class="form-group">
									{{ form.category.errors }}
									<label for="{{ form.category.id_for_label }}">Your category:</label>
									{{ form.category }}
							</div>
							<div class="custom-control custom-checkbox">
									{{ form.tags.errors }}
									<label for="{{ form.tags.id_for_label }}">Your tags:</label>
									{{ form.tags }}
							</div>
							<button type="submit">Enviar</button>
						</form>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/tag_create.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">

						<form method="post">
							{% csrf_token %}
							<div class="form-group">
								{{ form }}
							</div>
							<button type="submit">Add</button>
						</form>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/tag_delete.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">
						<form method="post">
							{% csrf_token %}
							<p>Are you sure you want to delete "{{ tag.tag }}"?</p>
							<input type="submit" value="Confirm">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/tag_list.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-6">
					<div class="block">
						<a href="{% url 'notes:tag_create' %}" class="badge badge-light mb-2">
							<h3>Add Tag</h3>
						</a>
						<table class="table table-striped">
							<thead class="thead-dark">
								<tr>
									<th scope="col">#</th>
									<th scope="col"></th>
									<th scope="col">Tag</th>
								</tr>
							</thead>
							<tbody>
								{% for item in tags %}
									<tr>
										<th scope="row">
											<a class="badge badge-danger" href="{% url 'notes:tag_delete' item.id %}">
													X
											</a>
										</th>
										<td>
											<h4>
												<a class="badge badge-primary" href="{% url 'notes:tag_update' item.id %}">
														Edit
												</a>
											</h4>
										</td>
										<td><h4>{{item.tag}}</h4></td>
									</tr>
								{% endfor %}
							</tbody>
						</table>

					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>

apps/notes/templates/notes/tag_update.html
{% extends 'base.html' %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-sm-4">
					<div class="block">
						<form method="post">
							{% csrf_token %}
							{{ form.as_p }}
							<input type="submit" value="Update">
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endblock %}
	</div>
</div>