Notes/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.notes.urls')),
]

apps/notes/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from apps.notes.views import *
app_name = 'notes'

urlpatterns = [
	path('sign_up/', register.as_view(), name='sign_up'),
	#
	path('log_in/', log_in, name='log_in'),
	#
	path('log_out/', log_out, name='log_out'),
	#
	path('', views.index, name='index'),
	# ex: /polls/5/
	path('<int:id>/', views.detail, name='detail'),
	#
	path('category/create/',category_create.as_view(), name='category_create'),
	#
	path('category/list/',category_list.as_view(), name='category_list'),
	#
	path('category/update/<int:pk>/',category_update.as_view(), name='category_update'),
	#
	path('category/delete/<int:pk>/',category_delete.as_view(), name='category_delete'),
	#
	path('tag/create/',tag_create, name='tag_create'),
	#
	path('tag/list/',tag_list, name='tag_list'),
	#
	path('tag/update/<int:pk>/',tag_update, name='tag_update'),
	#
	path('tag/delete/<int:pk>/',tag_delete, name='tag_delete'),
	#
	path('note/create/',note_create.as_view(), name='note_create'),
	#
	path('note/list/',note_list.as_view(), name='note_list'),
	#
	path('note/update/<int:pk>/',note_update.as_view(), name='note_update'),
	#
	path('note/delete/<int:pk>/',note_delete.as_view(), name='note_delete'),
	#
	path('note/detail/<int:pk>/',note_detail.as_view(), name='note_detail'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport"
					content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="icon" type="image/x-icon" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <link rel="shortcut icon" href="" />
    <title>{% block title %}Notes{% endblock %}</title>
  </head>
  <body>
		{% include  'navbar.html' %}
		<br>
		{% block content %}
		<h4>	base </h4>
		{% endblock %}
  </body>
  <footer>
    <script src="{% static 'js/scripts.js' %}"></script>
  </footer>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
<div class="row">
	<div class="col-sm">
		{% block content %}
		<div class="container-fluid">
			<!-- SIDE BLOCK -->
			<div class="col-sm-4" style="float:right;">
				<div class="block">
					<div class="card sidecard">
						<div class="card-body">
							<h5 class="card-title">Card title</h5>
							<h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
							<p class="card-text">
								Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
								tempor cididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
							</p>
							<a href="#" class="card-link">Card link</a>
							<a href="#" class="card-link">Another link</a>
						</div>
					</div>
				</div>
				<br>
				<div class="block">
					<div class="card sidecard">
						<img class="card-img-top" src="{% static 'img/my_notes_2.jpg' %}" alt="my_notes_2">
						<div class="card-body">
							<h5 class="card-title">Card title</h5>
							<p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,
								sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
								quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
								Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat
								nulla pariatur.
								Excepteur sint occaecat cupidatat non proident,
								sunt in culpa qui officia deserunt mollit anim id est laborum.
							</p>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item">Cras justo odio</li>
							<li class="list-group-item">Dapibus ac facilisis in</li>
							<li class="list-group-item">Vestibulum at eros</li>
						</ul>
						<div class="card-body">
							<a href="#" class="card-link">Card link</a>
							<a href="#" class="card-link">Another link</a>
						</div>
					</div>
				</div>
				<br>
				<!-- <div class="block"></div> -->
			</div>

			<!-- MAIN BLOCK -->
			<div class="col-sm-8 shadowblock">
				<table class="table table-striped">
					<thead class="thead-dark">
						<tr>
							<th scope="col">#</th>
							<th scope="col"></th>
							<th scope="col">Title</th>
							<!-- <th scope="col">Visibility</th>
							<th scope="col">Content</th> -->
							<th scope="col">Category</th>
							<th scope="col">Tags</th>
						</tr>
					</thead>
					<tbody>
						{% for item in list_notes %}
						<tr>
							<td><h4>#</h4></td>
							<td></td>
							<td>
								<h4>
									<a class="nav-link" href="{% url 'notes:note_detail' item.id %}">
										{{item.title}}
									</a>
								</h4>
							</td>
							<!--<td><h4>{{item.content}}</h4></td>
							<td><h4>{{item.visible_type}}</h4></td>-->
							<td>
								<span class="badge badge-secondary">{{item.category}}</span>
							</td>
							<td>
								{% for tag in item.all_tags %}
								<span class="badge badge-pill badge-warning">{{tag}}</span>
								{% endfor %}
							</td>
						</tr>
						{% endfor %}
					</tbody>
				</table>
			</div>

			<hr style="clear: right;">

		</div>
		{% endblock %}
	</div>
</div>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #83d0f2;">
	<div class="linksign">
		<a class="navbar-brand" href="{% url 'notes:index' %}" style="margin-left: 15%;">
			<!-- Home -->
			<!-- <img src="{% static 'img/notes_logo.png' %}" width="30" height="30" alt=""> -->
			<img src="{% static 'img/list-alt.svg' %}" alt="logo" width="30" height="30" >
		</a>
	</div>
	<div class="collapse navbar-collapse" id="navbarText">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link linksign" href="{% url 'notes:note_list' %}">Notes</a>
			</li>

			{% if user.is_staff %}
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'notes:category_list' %}">Categories</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link linksign" href="{% url 'notes:tag_list' %}">Tags</a>
				</li>
			{% else %}
				<li class="nav-item active">
				</li>
			{% endif %}

			{% if user.is_authenticated %}
				<li class="nav-item active">
					<a class="nav-link linksign" href="{% url 'notes:log_out' %}">Log Out</a>
				</li>
			{% else %}
				<li class="nav-item active">
					<a class="nav-link linksign" href="{% url 'notes:sign_up' %}">Sign Up</a>
				</li>
				<li class="nav-item active">
					<a class="nav-link linksign" href="{% url 'notes:log_in' %}">Log In</a>
				</li>
			{% endif %}
		</ul>
		<span class="navbar-text" style="color:black;">
			{% block welcome_message %}
				{% if user.is_authenticated %}
					<h5>Welcome to Notes {{ user.username }}!!!</h5>
				{% else %}
					Notes
				{% endif %}
			{% endblock %}
		</span>
	</div>
</nav>